#!/bin/bash

curl -n -X DELETE https://api.heroku.com/apps/ggfind/dynos \
  -H "Content-Type: application/json" \
  -H "Accept: application/vnd.heroku+json; version=3" \
  -H "Authorization: Bearer $AUTH_TOKEN"
