apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "whoogle.fullname" . }}
  labels:
    {{- include "whoogle.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "whoogle.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "whoogle.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- range .}}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      serviceAccountName: {{ include "whoogle.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: whoogle
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.conf }}
          env:
            {{- range $k,$v := . }}
            {{- if $v }}
            - name: {{ $k }}
              value: {{ tpl (toString $v) $ | quote }}
            {{- end }}
            {{- end }}
          {{- end }}
          ports:
            - name: http
              containerPort: {{ default 5000 .Values.conf.EXPOSE_PORT }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
              {{- if and .Values.conf.WHOOGLE_USER .Values.conf.WHOOGLE_PASS }}
              httpHeaders:
                - name: Authorization
                  value: Basic {{ b64enc (printf "%s:%s" .Values.conf.WHOOGLE_USER .Values.conf.WHOOGLE_PASS) }}
              {{- end }}
          readinessProbe:
            httpGet:
              path: /
              port: http
              {{- if and .Values.conf.WHOOGLE_USER .Values.conf.WHOOGLE_PASS }}
              httpHeaders:
                - name: Authorization
                  value: Basic {{ b64enc (printf "%s:%s" .Values.conf.WHOOGLE_USER .Values.conf.WHOOGLE_PASS) }}
              {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
