name: docker_main

on:
  workflow_run:
    workflows: ["tests"]
    branches: [live]
    types:
      - completed

# TODO: Needs refactoring to use reusable workflows and share w/ docker_tests
jobs:
  on-success:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: build and test (docker)
        run: |
          docker build --tag whoogle-search:test .
          docker run --publish 5000:5000 --detach --name whoogle-search-nocompose whoogle-search:test
          sleep 15
          docker exec whoogle-search-nocompose curl -f http://localhost:5000/healthz || exit 1
          
      - name: build and test (docker-compose)
        run: |
          docker rm -f whoogle-search-nocompose
          WHOOGLE_IMAGE="whoogle-search:test" docker compose up --detach
          sleep 15
          docker exec whoogle-search curl -f http://localhost:5000/healthz || exit 1
